import type { LucideProps } from "lucide-react";
import {
  UserCircle,
  LogOut,
  CheckCircle,
  XCircle,
  Clock,
  ChevronRight,
  ChevronLeft,
  ChartBarStacked,
  Users,
  User,
  FileText,
  Upload,
  Gauge,
  Menu,
  X,
  PlusCircle,
  Edit,
  Trash2,
  Search,
  Filter,
  ArrowUp,
  ArrowDown,
  CheckSquare,
  Target,
  BookOpen,
  Tag,
  Folder,
  Loader2,
  Rocket as Rocket01,
  Bookmark,
  ListPlus as Mix,
  AudioWaveform,
  Database,
  HardDrive,
  FileSearch,
  Ban,
  Check,
  ToggleLeft,
  ToggleRight
} from "lucide-react";

export type Icon = React.ComponentType<LucideProps>;

export const Icons = {
  rocket: Rocket01,
  bookmark: Bookmark,
  mix: Mix,
  userCircle: UserCircle,
  user: User,
  logout: LogOut,
  correct: CheckCircle,
  incorrect: XCircle,
  clock: Clock,
  next: ChevronRight,
  previous: ChevronLeft,
  chart: ChartBarStacked,
  users: Users,
  questions: FileText,
  upload: Upload,
  dashboard: Gauge,
  menu: Menu,
  close: X,
  add: PlusCircle,
  edit: Edit,
  delete: Trash2,
  search: Search,
  filter: Filter,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  check: CheckSquare,
  target: Target,
  topic: BookOpen,
  tag: Tag,
  folder: Folder,
  spinner: Loader2,
  sound: AudioWaveform,
  database: Database,
  hardDrive: HardDrive,
  details: FileSearch,
  ban: Ban,
  checkmark: Check,
  active: ToggleRight,
  inactive: ToggleLeft,
  key: (props: any) => ( // Added key icon
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}>
      <path d="M21 2l-2 2m-7.61 7.61a5.5 5.5 0 1 1-7.778 7.778 5.5 5.5 0 0 1 7.777-7.777zm0 0L15.5 7.5m0 0l3 3L22 7l-3-3m-3.5 3.5L19 4"></path>
    </svg>
  )
};